//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_AAnarByStatus
    {
        public int ID { get; set; }
        public Nullable<int> LineID { get; set; }
        public Nullable<int> Segment { get; set; }
        public Nullable<double> Ti { get; set; }
        public Nullable<double> Si { get; set; }
        public Nullable<double> Vi { get; set; }
        public Nullable<double> Tr { get; set; }
        public Nullable<double> Sr { get; set; }
        public Nullable<double> Vr { get; set; }
        public Nullable<double> St { get; set; }
        public Nullable<double> Vv { get; set; }
    }
}
