//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Hours
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> StartHour { get; set; }
        public Nullable<bool> IsWorkingDay { get; set; }
        public int LineID { get; set; }
        public int Spin { get; set; }
    
        public virtual A_Lines A_Lines { get; set; }
    }
}
