//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Stopper
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<double> lat { get; set; }
        public Nullable<double> lon { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<int> Zone { get; set; }
        public string Links { get; set; }
        public string Services { get; set; }
        public Nullable<double> latPos1 { get; set; }
        public Nullable<double> lonPos1 { get; set; }
        public Nullable<double> latPos2 { get; set; }
        public Nullable<double> lonPos2 { get; set; }
        public string Access1 { get; set; }
        public string Access2 { get; set; }
    }
}
