//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agenda
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public bool Destacado { get; set; }
        public System.DateTime FechaPublicacion { get; set; }
        public Nullable<System.DateTime> FechaCaducidad { get; set; }
        public Nullable<int> Portal { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Imagen { get; set; }
        public Nullable<int> CantidadImagen { get; set; }
        public Nullable<bool> Nacional { get; set; }
        public int Evento { get; set; }
        public string UrlTitulo { get; set; }
        public string ShortURL { get; set; }
    
        public virtual Portal Portal1 { get; set; }
    }
}
