//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AH_Terrassa_schedule
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Catalunya { get; set; }
        public Nullable<System.DateTime> Provenca { get; set; }
        public Nullable<System.DateTime> Gracia { get; set; }
        public Nullable<System.DateTime> Muntaner { get; set; }
        public Nullable<System.DateTime> Sarria { get; set; }
        public Nullable<System.DateTime> Peu { get; set; }
        public Nullable<System.DateTime> Vallvidrera { get; set; }
        public Nullable<System.DateTime> Planes { get; set; }
        public Nullable<System.DateTime> Floresta { get; set; }
        public Nullable<System.DateTime> Valldoreix { get; set; }
        public Nullable<System.DateTime> Cugat { get; set; }
        public Nullable<System.DateTime> Mirasol { get; set; }
        public Nullable<System.DateTime> HGeneral { get; set; }
        public Nullable<System.DateTime> Rubi { get; set; }
        public Nullable<System.DateTime> Fonts { get; set; }
        public Nullable<System.DateTime> Terrassa { get; set; }
        public Nullable<int> Spin { get; set; }
    }
}
