//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alertas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alertas()
        {
            this.AlertasAfiliados = new HashSet<AlertasAfiliados>();
        }
    
        public int IdAlerta { get; set; }
        public Nullable<System.Guid> IdUsuario { get; set; }
        public Nullable<int> IdSolicitud { get; set; }
        public Nullable<int> IdComunidad { get; set; }
        public Nullable<int> IdPoblacion { get; set; }
        public System.DateTime FechaActivacion { get; set; }
        public Nullable<System.DateTime> FechaCaducidad { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public bool Leido { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlertasAfiliados> AlertasAfiliados { get; set; }
        public virtual Comunidad Comunidad { get; set; }
        public virtual Financiacion_Solicitud Financiacion_Solicitud { get; set; }
        public virtual Munincipios Munincipios { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
