//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertasAfiliados
    {
        public int IdAlerta { get; set; }
        public System.Guid IdUsuario { get; set; }
        public bool Leido { get; set; }
    
        public virtual Alertas Alertas { get; set; }
    }
}
