//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnarBy_TerresaRealTime
    {
        public int ID { get; set; }
        public Nullable<int> spin { get; set; }
        public Nullable<double> Latitud { get; set; }
        public Nullable<double> Longitd { get; set; }
        public Nullable<double> LatitudFuture { get; set; }
        public Nullable<double> LongitdFuture { get; set; }
        public Nullable<double> Spped { get; set; }
        public Nullable<double> Distance { get; set; }
        public Nullable<double> Time { get; set; }
        public Nullable<double> Co2 { get; set; }
        public string Name { get; set; }
    }
}
