//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnuncioCochesExtra
    {
        public int IDAnuncioCoche { get; set; }
        public Nullable<byte> AireAcondicionado { get; set; }
        public Nullable<byte> Alarma { get; set; }
        public Nullable<byte> Climatizador { get; set; }
        public Nullable<byte> Antinieblas { get; set; }
        public Nullable<byte> ControlTraccion { get; set; }
        public Nullable<byte> CargadorCD { get; set; }
        public Nullable<byte> Inmovilizador { get; set; }
        public Nullable<byte> CierreCentralizado { get; set; }
        public Nullable<byte> ControlVelocidad { get; set; }
        public Nullable<byte> Parktronic { get; set; }
        public Nullable<byte> Navegador { get; set; }
        public Nullable<byte> Ordenador { get; set; }
        public Nullable<byte> Airbag { get; set; }
        public Nullable<byte> ElevalunasElectrico { get; set; }
        public Nullable<byte> ABS { get; set; }
        public Nullable<byte> ESP { get; set; }
        public Nullable<byte> DireccionAsistida { get; set; }
        public Nullable<byte> LlantasAleacion { get; set; }
        public Nullable<byte> FarosXenon { get; set; }
        public Nullable<byte> IsoFix { get; set; }
        public Nullable<byte> Techo { get; set; }
    }
}
