//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apoyos
    {
        public int ID { get; set; }
        public string Apoyo { get; set; }
        public string NombreComercial { get; set; }
        public string NombreFiscal { get; set; }
        public string CIF { get; set; }
        public string Actividad { get; set; }
        public string DireccionComercial { get; set; }
        public string Localidad { get; set; }
        public string Provincia { get; set; }
        public string Comunidad { get; set; }
        public string CodigoPostal { get; set; }
        public string Telefonos { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Email2 { get; set; }
        public string Web { get; set; }
        public string Otros { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Marcas { get; set; }
    }
}
