//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class botigues
    {
        public int Id { get; set; }
        public Nullable<int> Idprovincies { get; set; }
        public string codi1 { get; set; }
        public string codi2 { get; set; }
        public string codi3 { get; set; }
        public string codi4 { get; set; }
        public string codi5 { get; set; }
        public string codi6 { get; set; }
        public string codi7 { get; set; }
        public string codi8 { get; set; }
        public string codi9 { get; set; }
        public string codi0 { get; set; }
        public Nullable<int> num_associat { get; set; }
        public Nullable<System.DateTime> alta { get; set; }
        public Nullable<System.DateTime> baixa { get; set; }
        public bool actiu { get; set; }
        public bool deutor { get; set; }
        public string nom_comercial { get; set; }
        public string nom { get; set; }
        public string admin { get; set; }
        public string dni_admin { get; set; }
        public string admin1 { get; set; }
        public string dni_admin1 { get; set; }
        public string direccio { get; set; }
        public string direcio1 { get; set; }
        public string cp { get; set; }
        public string cp1 { get; set; }
        public string poblacio { get; set; }
        public string poblacio1 { get; set; }
        public string provincia { get; set; }
        public string provincia1 { get; set; }
        public string comunitat { get; set; }
        public string comunitat1 { get; set; }
        public string nif { get; set; }
        public string telf11 { get; set; }
        public string telf1 { get; set; }
        public string telf22 { get; set; }
        public string telf2 { get; set; }
        public string codi_banc { get; set; }
        public string codi_oficina { get; set; }
        public string codi_control { get; set; }
        public string compte_c { get; set; }
        public string fax { get; set; }
        public string mail1 { get; set; }
        public string mail2 { get; set; }
        public string url { get; set; }
        public string per1 { get; set; }
        public string per2 { get; set; }
        public string per3 { get; set; }
        public string tel_mobil_1 { get; set; }
        public string tel_mobil_2 { get; set; }
        public string tel_mobil_3 { get; set; }
        public string bprestec1 { get; set; }
        public string bprestec2 { get; set; }
        public string bprestec3 { get; set; }
        public string bprestec4 { get; set; }
        public string bprestec5 { get; set; }
        public string bprestec11 { get; set; }
        public string bprestec22 { get; set; }
        public string bprestec33 { get; set; }
        public string bprestec44 { get; set; }
        public string bprestec55 { get; set; }
        public string bprestec66 { get; set; }
        public string bprestec77 { get; set; }
        public string bprestec88 { get; set; }
        public string bprestec99 { get; set; }
        public string bprestec00 { get; set; }
        public string banc1 { get; set; }
        public string banc2 { get; set; }
        public string banc3 { get; set; }
        public string banc4 { get; set; }
        public string banc5 { get; set; }
        public string oficina1 { get; set; }
        public string oficina2 { get; set; }
        public string oficina3 { get; set; }
        public string oficina4 { get; set; }
        public string oficina5 { get; set; }
        public string dc1 { get; set; }
        public string dc2 { get; set; }
        public string dc3 { get; set; }
        public string dc4 { get; set; }
        public string dc5 { get; set; }
        public string cc1 { get; set; }
        public string cc2 { get; set; }
        public string cc3 { get; set; }
        public string cc4 { get; set; }
        public string cc5 { get; set; }
        public string observacions { get; set; }
        public string notes { get; set; }
        public bool Zona_A { get; set; }
        public bool Zona_B { get; set; }
    }
}
