//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Canasta
    {
        public int Id { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public Nullable<int> TiendaItemID { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<System.DateTime> FechaNuevo { get; set; }
        public Nullable<System.DateTime> FechaCompra { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
