//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientesFinanciacion
    {
        public int ID { get; set; }
        public Nullable<int> IDFINANCIACION { get; set; }
        public Nullable<System.Guid> AFILIADOID { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO1 { get; set; }
        public string APELLIDO2 { get; set; }
        public string TIPODOCUMENTODNI { get; set; }
        public string DNI { get; set; }
        public Nullable<System.DateTime> FECHA_NACIEMIENTO { get; set; }
        public string DIRECCION { get; set; }
        public string CP { get; set; }
        public Nullable<int> LOCALIDAD { get; set; }
        public Nullable<int> PROVINCIA { get; set; }
        public Nullable<int> COMUNIDAD { get; set; }
        public Nullable<int> PAIS { get; set; }
        public string TELEFONO { get; set; }
        public string FAX { get; set; }
        public string MOBIL { get; set; }
        public string EMAIL { get; set; }
        public string ESTADO_CIVIL { get; set; }
        public string NACIONALIDAD { get; set; }
        public Nullable<System.DateTime> FECHALIMITERESIDENCIAPERMISO { get; set; }
        public string PROFESION { get; set; }
        public Nullable<System.DateTime> ANTIGUEDAD { get; set; }
        public string EMPRESA { get; set; }
        public string DIRECCION_EMPRESA { get; set; }
        public string CP_EMPRESA { get; set; }
        public Nullable<int> LOCALIDAD_EMPRESA { get; set; }
        public Nullable<int> PROVINCIA_EMPRESA { get; set; }
        public Nullable<int> COMUNIDAD_EMPRESA { get; set; }
        public Nullable<int> PAIS_EMPRESA { get; set; }
        public string TELEFONO_EMPRESA { get; set; }
        public string FAX_EMPRESA { get; set; }
        public string MOBIL_EMPRESA { get; set; }
        public string TIPO_CONTRATO { get; set; }
        public Nullable<double> INGREOSOSNETOS { get; set; }
        public Nullable<double> INGRESOSVARIABLES { get; set; }
        public string NOMBREAVAL1 { get; set; }
        public string APELLIDO1AVAL1 { get; set; }
        public string APELLIDO2AVAL1 { get; set; }
        public string TIPODOCUMENTODNIAVAL1 { get; set; }
        public string DNIAVAL1 { get; set; }
        public Nullable<System.DateTime> FECHA_NACIEMIENTOAVAL1 { get; set; }
        public string DIRECCIONAVAL1 { get; set; }
        public string CPAVAL1 { get; set; }
        public Nullable<int> LOCALIDADAVAL1 { get; set; }
        public Nullable<int> PROVINCIAAVAL1 { get; set; }
        public Nullable<int> COMUNIDADAVAL1 { get; set; }
        public Nullable<int> PAISAVAL1 { get; set; }
        public string TELEFONOAVAL1 { get; set; }
        public string FAXAVAL1 { get; set; }
        public string MOBILAVAL1 { get; set; }
        public string EMAILAVAL1 { get; set; }
        public string ESTADO_CIVILAVAL1 { get; set; }
        public string NACIONALIDADAVAL1 { get; set; }
        public Nullable<System.DateTime> FECHALIMITERESIDENCIAPERMISOAVAL1 { get; set; }
        public string PROFESIONAVAL1 { get; set; }
        public Nullable<System.DateTime> ANTIGUEDADAVAL1 { get; set; }
        public string EMPRESAAVAL1 { get; set; }
        public string DIRECCION_EMPRESAAVAL1 { get; set; }
        public string CP_EMPRESAAVAL1 { get; set; }
        public Nullable<int> LOCALIDAD_EMPRESAAVAL1 { get; set; }
        public Nullable<int> PROVINCIA_EMPRESAAVAL1 { get; set; }
        public Nullable<int> COMUNIDAD_EMPRESAAVAL1 { get; set; }
        public Nullable<int> PAIS_EMPRESAAVAL1 { get; set; }
        public string TELEFONO_EMPRESAAVAL1 { get; set; }
        public string FAX_EMPRESAAVAL1 { get; set; }
        public string MOBIL_EMPRESAAVAL1 { get; set; }
        public string TIPO_CONTRATOAVAL1 { get; set; }
        public Nullable<double> INGREOSOSNETOSAVAL1 { get; set; }
        public Nullable<double> INGRESOSVARIABLESAVAL1 { get; set; }
        public string NOMBREAVAL2 { get; set; }
        public string APELLIDO1AVAL2 { get; set; }
        public string APELLIDO2AVAL2 { get; set; }
        public string TIPODOCUMENTODNIAVAL2 { get; set; }
        public string DNIAVAL2 { get; set; }
        public Nullable<System.DateTime> FECHA_NACIEMIENTOAVAL2 { get; set; }
        public string DIRECCIONAVAL2 { get; set; }
        public string CPAVAL2 { get; set; }
        public Nullable<int> LOCALIDADAVAL2 { get; set; }
        public Nullable<int> PROVINCIAAVAL2 { get; set; }
        public Nullable<int> COMUNIDADAVAL2 { get; set; }
        public Nullable<int> PAISAVAL2 { get; set; }
        public string TELEFONOAVAL2 { get; set; }
        public string FAXAVAL2 { get; set; }
        public string MOBILAVAL2 { get; set; }
        public string EMAILAVAL2 { get; set; }
        public string ESTADO_CIVILAVAL2 { get; set; }
        public string NACIONALIDADAVAL2 { get; set; }
        public Nullable<System.DateTime> FECHALIMITERESIDENCIAPERMISOAVAL2 { get; set; }
        public string PROFESIONAVAL2 { get; set; }
        public Nullable<System.DateTime> ANTIGUEDADAVAL2 { get; set; }
        public string EMPRESAAVAL2 { get; set; }
        public string DIRECCION_EMPRESAAVAL2 { get; set; }
        public string CP_EMPRESAAVAL2 { get; set; }
        public Nullable<int> LOCALIDAD_EMPRESAAVAL2 { get; set; }
        public Nullable<int> PROVINCIA_EMPRESAAVAL2 { get; set; }
        public Nullable<int> COMUNIDAD_EMPRESAAVAL2 { get; set; }
        public Nullable<int> PAIS_EMPRESAAVAL2 { get; set; }
        public string TELEFONO_EMPRESAAVAL2 { get; set; }
        public string FAX_EMPRESAAVAL2 { get; set; }
        public string MOBIL_EMPRESAAVAL2 { get; set; }
        public string TIPO_CONTRATOAVAL2 { get; set; }
        public Nullable<double> INGREOSOSNETOSAVAL2 { get; set; }
        public Nullable<double> INGRESOSVARIABLESAVAL2 { get; set; }
        public Nullable<int> TIPUSINMUEBLE { get; set; }
        public Nullable<double> CUOTAALQUILER { get; set; }
        public Nullable<double> CUOTAHIPOTECA { get; set; }
    }
}
