//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clients
    {
        public int Id_1 { get; set; }
        public Nullable<System.DateTime> data_alta { get; set; }
        public Nullable<System.DateTime> data_aprovacio { get; set; }
        public Nullable<int> num_autoritzacio { get; set; }
        public string num_autoritzacio1 { get; set; }
        public string aprovada { get; set; }
        public string formulitzada { get; set; }
        public string denegada { get; set; }
        public string operadora { get; set; }
        public Nullable<double> comissio_cv { get; set; }
        public Nullable<double> comissio_banc { get; set; }
        public string entitat_financera { get; set; }
        public string oficina_sig { get; set; }
        public string direccio_oficina { get; set; }
        public string cp_oficina { get; set; }
        public string comercial_entitat_finan { get; set; }
        public string tel_entitat_financera { get; set; }
        public string fax_entitat_financera { get; set; }
        public string mail_entitat_financera { get; set; }
        public string poblacio_financera { get; set; }
        public string botiga { get; set; }
        public string codi_botiga { get; set; }
        public string poblacio_botiga { get; set; }
        public string nom_client { get; set; }
        public string cognom1_client { get; set; }
        public string cognom2_client { get; set; }
        public string nif_client { get; set; }
        public Nullable<System.DateTime> dnaix_client { get; set; }
        public string direcció_client { get; set; }
        public string cp_client { get; set; }
        public string poblacio_client { get; set; }
        public string provincia { get; set; }
        public string tel_part_client { get; set; }
        public string tel_feina_client { get; set; }
        public string tel_mobil_client { get; set; }
        public string e_civil_client { get; set; }
        public Nullable<int> per_carrec_client { get; set; }
        public Nullable<int> menors_client { get; set; }
        public Nullable<int> adults_client { get; set; }
        public string laboral_client { get; set; }
        public string activitat_client { get; set; }
        public string professio_client { get; set; }
        public string antiguitat_client { get; set; }
        public string empresa_client { get; set; }
        public string direccio_empresa_client { get; set; }
        public string cp_empresa_client { get; set; }
        public string poblacio_empresa_client { get; set; }
        public string tel_empresa_client { get; set; }
        public Nullable<double> ing_nets_client { get; set; }
        public Nullable<double> ing_var_client { get; set; }
        public string lloguer_client { get; set; }
        public string hipo_client { get; set; }
        public string tipus_viv_client { get; set; }
        public Nullable<int> valor_viv_client { get; set; }
        public Nullable<int> carregues_client { get; set; }
        public Nullable<int> quota_lloguer_client { get; set; }
        public Nullable<int> quota_hipo_client { get; set; }
        public string nom_titular1 { get; set; }
        public string cognom1_titular1 { get; set; }
        public string cognom2_titular1 { get; set; }
        public string nif_titular1 { get; set; }
        public Nullable<System.DateTime> dnaix_titular1 { get; set; }
        public string direcció_titular1 { get; set; }
        public string cp_titular1 { get; set; }
        public string poblacio_titular1 { get; set; }
        public string provincia_1 { get; set; }
        public string tel_part_titular1 { get; set; }
        public string tel_feina_titular1 { get; set; }
        public string tel_mobil_titular1 { get; set; }
        public string e_civil_titular1 { get; set; }
        public Nullable<int> per_carrec_titular1 { get; set; }
        public Nullable<int> menors_titular1 { get; set; }
        public Nullable<int> adults_titular1 { get; set; }
        public string laboral_titular1 { get; set; }
        public string activitat_titular1 { get; set; }
        public string professio_titular1 { get; set; }
        public string antiguitat_titular1 { get; set; }
        public string empresa_titular1 { get; set; }
        public string direccio_empresa_titular1 { get; set; }
        public string cp_empresa_titular1 { get; set; }
        public string poblacio_empresa_titular1 { get; set; }
        public string tel_empresa_titular1 { get; set; }
        public Nullable<double> ing_nets_titular1 { get; set; }
        public Nullable<double> ing_var_titular1 { get; set; }
        public string lloguer_titular1 { get; set; }
        public string hipo_titular1 { get; set; }
        public string tipus_viv_titular1 { get; set; }
        public Nullable<int> valor_viv_titular1 { get; set; }
        public Nullable<int> carregues_titular1 { get; set; }
        public Nullable<int> quota_lloguer_titular1 { get; set; }
        public Nullable<int> quota_hipo_titular1 { get; set; }
        public string nom_titular2 { get; set; }
        public string cognom1_titular2 { get; set; }
        public string cognom2_titular2 { get; set; }
        public string nif_titular2 { get; set; }
        public Nullable<System.DateTime> dnaix_titular2 { get; set; }
        public string direccio_titular2 { get; set; }
        public string cp_titular2 { get; set; }
        public string poblacio_titular2 { get; set; }
        public string provincia_2 { get; set; }
        public string tel_part_titular2 { get; set; }
        public string tel_feina_titular2 { get; set; }
        public string tel_mobil_titular2 { get; set; }
        public string e_civil_titular2 { get; set; }
        public Nullable<int> per_carrec_titular2 { get; set; }
        public Nullable<int> menors_titular2 { get; set; }
        public Nullable<int> adults_titular2 { get; set; }
        public string laboral_titular2 { get; set; }
        public string activitat_titular2 { get; set; }
        public string professio_titular2 { get; set; }
        public string antiguitat_titular2 { get; set; }
        public string empresa_titular2 { get; set; }
        public string direccio_empresa_titular2 { get; set; }
        public string cp_empresa_titular2 { get; set; }
        public string poblacio_empresa_titular2 { get; set; }
        public string tel_empresa_titular2 { get; set; }
        public Nullable<double> ing_nets_titular2 { get; set; }
        public Nullable<double> ing_var_titular2 { get; set; }
        public string lloguer_titular2 { get; set; }
        public string hipo_titular2 { get; set; }
        public string tipus_viv_titular2 { get; set; }
        public Nullable<float> valor_viv_titular2 { get; set; }
        public Nullable<int> carregues_titular2 { get; set; }
        public Nullable<int> quota_lloguer_titular2 { get; set; }
        public Nullable<int> quota_hipo_titular2 { get; set; }
        public string vehicle { get; set; }
        public string casament { get; set; }
        public string marca { get; set; }
        public string model { get; set; }
        public string matricula { get; set; }
        public Nullable<int> valor_adquisicio { get; set; }
        public Nullable<System.DateTime> any_matriculacio { get; set; }
        public string nou { get; set; }
        public string usat { get; set; }
        public Nullable<double> import { get; set; }
        public Nullable<double> interes { get; set; }
        public string diesel { get; set; }
        public string gasolina { get; set; }
        public Nullable<double> quota { get; set; }
        public Nullable<int> terminis { get; set; }
        public Nullable<int> carencia { get; set; }
        public string despeses { get; set; }
        public string entitat { get; set; }
        public string assegurança { get; set; }
        public string oficina { get; set; }
        public string dc { get; set; }
        public string cc { get; set; }
        public string observacions { get; set; }
        public string nacionalitat_client { get; set; }
        public Nullable<System.DateTime> venc_permis_res { get; set; }
        public string nbastidor { get; set; }
        public string cubicatge { get; set; }
        public string nacionalitat_titular1 { get; set; }
        public string nacionalitat_titular2 { get; set; }
        public Nullable<System.DateTime> venc_permis_res1 { get; set; }
        public Nullable<System.DateTime> venc_permis_res2 { get; set; }
    }
}
