//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConductorSeguroFlotante
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string DNI { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public System.DateTime FechaCarnet { get; set; }
        public int IdTipoConductorSeguroFlotante { get; set; }
        public int IdSeguroFlotante { get; set; }
    }
}
