//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consulta_etiquetes_A
    {
        public string nom { get; set; }
        public string nom_comercial { get; set; }
        public string direccio { get; set; }
        public string cp { get; set; }
        public string poblacio { get; set; }
        public string provincia { get; set; }
        public bool Zona_A { get; set; }
        public bool actiu { get; set; }
    }
}
