//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DerechosReales
    {
        public int ID { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string CV { get; set; }
        public string Periodo { get; set; }
        public string CC { get; set; }
        public string CIL { get; set; }
        public string C { get; set; }
        public string KW { get; set; }
        public string CVF { get; set; }
        public Nullable<decimal> C_100 { get; set; }
        public string CO2 { get; set; }
    }
}
