//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DerechoRealPorcientos
    {
        public int ID { get; set; }
        public Nullable<double> Porciento_1 { get; set; }
        public Nullable<double> Porciento_2 { get; set; }
        public Nullable<double> Porciento_3 { get; set; }
        public Nullable<double> Porciento_4 { get; set; }
        public Nullable<double> Porciento_5 { get; set; }
        public Nullable<double> Porciento_6 { get; set; }
        public Nullable<double> Porciento_7 { get; set; }
        public Nullable<double> Porciento_8 { get; set; }
        public Nullable<double> Porciento_9 { get; set; }
        public Nullable<double> Porciento_10 { get; set; }
        public Nullable<double> Porciento_12 { get; set; }
        public Nullable<double> Porciento_13 { get; set; }
        public Nullable<double> Porciento_14 { get; set; }
        public Nullable<double> Porciento_15 { get; set; }
        public string Anyo { get; set; }
        public Nullable<int> idComunidad { get; set; }
        public Nullable<double> Porcentaje { get; set; }
        public string Excepcion { get; set; }
    }
}
