//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentosReclamacion
    {
        public int ID { get; set; }
        public string Idioma { get; set; }
        public string NombreFichero { get; set; }
        public string RutaDocumento { get; set; }
        public Nullable<int> IDComunidad { get; set; }
        public string Titulo { get; set; }
        public Nullable<System.DateTime> FechaPublicacion { get; set; }
    
        public virtual Comunidad Comunidad { get; set; }
    }
}
