//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Est_Log
    {
        public int ID { get; set; }
        public string idModulo { get; set; }
        public string Descripcion { get; set; }
        public string ExcepcionMessage { get; set; }
        public string ExcepcionSource { get; set; }
        public string ExcepcionStackTrace { get; set; }
        public string Metodo { get; set; }
        public string Documento { get; set; }
    }
}
