//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadisticasVNTotalesTemp
    {
        public int ID { get; set; }
        public string TipoVehiculo { get; set; }
        public string Canal { get; set; }
        public string MarcaVehiculo { get; set; }
        public string ModeloVehiculo { get; set; }
        public string Segmento { get; set; }
        public string Anyo { get; set; }
        public Nullable<int> Enero { get; set; }
        public Nullable<int> Febrero { get; set; }
        public Nullable<int> Marzo { get; set; }
        public Nullable<int> Abril { get; set; }
        public Nullable<int> Mayo { get; set; }
        public Nullable<int> Junio { get; set; }
        public Nullable<int> Julio { get; set; }
        public Nullable<int> Agosto { get; set; }
        public Nullable<int> Septiembre { get; set; }
        public Nullable<int> Octubre { get; set; }
        public Nullable<int> Noviembre { get; set; }
        public Nullable<int> Diciembre { get; set; }
        public Nullable<int> Total { get; set; }
    }
}
