//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadisticasVNSemanalesTemp
    {
        public int ID { get; set; }
        public string TipoVehiculo { get; set; }
        public string Canal { get; set; }
        public string MarcaVehiculo { get; set; }
        public string ModeloVehiculo { get; set; }
        public string Segmento { get; set; }
        public string CodigoPostal { get; set; }
        public string Municipios { get; set; }
        public string Anyo { get; set; }
        public string Mes { get; set; }
        public Nullable<int> Semana1 { get; set; }
        public Nullable<int> Semana2 { get; set; }
        public Nullable<int> Semana3 { get; set; }
        public Nullable<int> Semana4 { get; set; }
        public Nullable<int> Semana5 { get; set; }
        public Nullable<int> Total { get; set; }
    }
}
