//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturacionFichRecDevueltos
    {
        public int Id { get; set; }
        public string NombreFichero { get; set; }
        public int NumeroRecibos { get; set; }
        public double ImporteTotal { get; set; }
        public int IdEstadoFichDevuelto { get; set; }
        public System.DateTime FechaRecepcion { get; set; }
        public Nullable<System.DateTime> FechaProcesado { get; set; }
    
        public virtual FacturacionEstadoFichDevuelto FacturacionEstadoFichDevuelto { get; set; }
    }
}
