//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaServicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FacturaServicio()
        {
            this.FacturaDetalle = new HashSet<FacturaDetalle>();
            this.UsuariosServicios = new HashSet<UsuariosServicios>();
            this.UsuariosServiciosSeguimiento = new HashSet<UsuariosServiciosSeguimiento>();
        }
    
        public int Id { get; set; }
        public int IdEmpresa { get; set; }
        public string Descripcion { get; set; }
        public Nullable<double> Precio { get; set; }
        public Nullable<double> TipoIva { get; set; }
        public int IdTipoFacturaServicio { get; set; }
        public string TipoAnuncio { get; set; }
        public Nullable<bool> Destacado { get; set; }
        public Nullable<bool> Carrusel { get; set; }
        public Nullable<bool> Profesional { get; set; }
        public Nullable<bool> Particular { get; set; }
        public Nullable<int> IdNumeradoresCab { get; set; }
        public Nullable<int> IdRelacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturaDetalle> FacturaDetalle { get; set; }
        public virtual NumeradoresCab NumeradoresCab { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuariosServicios> UsuariosServicios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuariosServiciosSeguimiento> UsuariosServiciosSeguimiento { get; set; }
    }
}
