//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Facturacion()
        {
            this.FacturaGlobal = new HashSet<FacturaGlobal>();
        }
    
        public int Id { get; set; }
        public int IdEmpresa { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public int IdEstadoRemesa { get; set; }
        public Nullable<System.DateTime> FechaGeneracion { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
        public string NombreFichero { get; set; }
        public Nullable<double> Base { get; set; }
        public Nullable<double> Iva { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<int> NumeroRecibos { get; set; }
        public Nullable<int> IdNumeradoresLin { get; set; }
    
        public virtual Empresas Empresas { get; set; }
        public virtual FacturacionRemesaEstado FacturacionRemesaEstado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturaGlobal> FacturaGlobal { get; set; }
    }
}
