//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaGlobal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FacturaGlobal()
        {
            this.FacturaDetalle = new HashSet<FacturaDetalle>();
        }
    
        public int Id { get; set; }
        public Nullable<int> NumeroFactura { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public Nullable<int> Departamento { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<System.Guid> IdCliente { get; set; }
        public Nullable<int> IdTipoIva { get; set; }
        public Nullable<double> PorcentajeIva { get; set; }
        public string FormaDePago { get; set; }
        public Nullable<double> Iva { get; set; }
        public Nullable<double> BaseIva { get; set; }
        public Nullable<double> Total { get; set; }
        public string TipoFactura { get; set; }
        public Nullable<int> IdFacturacion { get; set; }
        public string SerieFactura { get; set; }
        public string Canal { get; set; }
        public string Detalle { get; set; }
        public Nullable<bool> Cobrado { get; set; }
        public string NombreFiscal { get; set; }
    
        public virtual Empresas Empresas { get; set; }
        public virtual Facturacion Facturacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturaDetalle> FacturaDetalle { get; set; }
        public virtual TipoIva TipoIva { get; set; }
    }
}
