//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Financiacion_Usuario_Banco
    {
        public int Id { get; set; }
        public System.Guid IdUsuario { get; set; }
        public string Banco { get; set; }
        public string Entidad { get; set; }
        public string Oficina { get; set; }
        public string DC { get; set; }
        public string Cuenta { get; set; }
        public string Notas { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
