//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Financiacion_Configuracion
    {
        public int IdConfiguracion { get; set; }
        public bool AvisosAfiliados { get; set; }
        public bool OperacionesAprobadas { get; set; }
        public bool OperacionesCondicionadas { get; set; }
        public bool RecordatorioFirmar { get; set; }
        public bool RecordatorioCirculacion { get; set; }
        public bool EmailCambioEstado { get; set; }
        public bool AvisosEmpleados { get; set; }
        public bool NuevasSolicitudes { get; set; }
        public bool EmailSolicitud { get; set; }
        public string EmailNuevaSolicitud { get; set; }
        public bool AvisosPreAprobadas { get; set; }
        public bool AvisosPreCondicionadas { get; set; }
    }
}
