//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Financiacion_OLD
    {
        public int ID { get; set; }
        public Nullable<int> IDBANCF { get; set; }
        public Nullable<int> NUM_AUT { get; set; }
        public string NUM_OPE { get; set; }
        public Nullable<int> TYPE { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<System.DateTime> FECHA_ACEEPTACION { get; set; }
        public Nullable<int> FINANCIERAID { get; set; }
        public Nullable<int> MARCAID { get; set; }
        public string MATRICULA { get; set; }
        public Nullable<double> VALOR_NETO { get; set; }
        public Nullable<int> MODELID { get; set; }
        public string CUBICAGE { get; set; }
        public string NBASCTIDOR { get; set; }
        public Nullable<System.DateTime> FECHA_MATRICULACION { get; set; }
        public Nullable<int> STATUSCOCHE { get; set; }
        public Nullable<int> COMBUSTIBLETIPO { get; set; }
        public Nullable<double> PRESTAMONETO { get; set; }
        public Nullable<double> QUOTAMENSUAL { get; set; }
        public Nullable<int> PERIODO { get; set; }
        public Nullable<double> INTERES { get; set; }
        public string DESPESES { get; set; }
        public string COMISION { get; set; }
        public Nullable<bool> AEGURADO { get; set; }
        public string OBSERVACIONES { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    }
}
