//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Financiacion_Usuario_Datos
    {
        public int Id { get; set; }
        public System.Guid IdUsuario { get; set; }
        public bool PuedeFinanciar { get; set; }
        public string Motivo { get; set; }
        public bool TieneTienda { get; set; }
        public string Foto1 { get; set; }
        public string Foto2 { get; set; }
        public string Foto3 { get; set; }
        public bool ActivarAvisos { get; set; }
        public string EmailAvisos { get; set; }
        public string Observaciones { get; set; }
        public string Comentarios { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
