//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Financiacion_Solicitud_Fichero
    {
        public int IdFichero { get; set; }
        public int IdSolicitud { get; set; }
        public string Fichero { get; set; }
    
        public virtual Financiacion_Solicitud Financiacion_Solicitud { get; set; }
    }
}
