//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Financiacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Financiacion()
        {
            this.FinanciacionBanco = new HashSet<FinanciacionBanco>();
            this.FinanciacionComprador = new HashSet<FinanciacionComprador>();
        }
    
        public int ID { get; set; }
        public System.Guid AfiliadoID { get; set; }
        public int StatusID { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public Nullable<System.DateTime> FechaAceptacion { get; set; }
        public string Vendedor { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public string Vehiculo { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Cilindrada { get; set; }
        public Nullable<int> Puertas { get; set; }
        public string Matricula { get; set; }
        public string Bastidor { get; set; }
        public Nullable<System.DateTime> Matriculacion { get; set; }
        public string Combustible { get; set; }
        public Nullable<decimal> ImporteVehiculo { get; set; }
        public Nullable<decimal> ImportePrestamo { get; set; }
        public Nullable<int> NumCuotas { get; set; }
        public Nullable<double> TipoInteres { get; set; }
        public Nullable<decimal> ImporteCuota { get; set; }
        public Nullable<bool> Seguro { get; set; }
        public Nullable<decimal> Comision { get; set; }
        public Nullable<int> Carencia { get; set; }
        public Nullable<decimal> GastosFinanciados { get; set; }
        public string Observaciones { get; set; }
        public string Operador { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinanciacionBanco> FinanciacionBanco { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinanciacionComprador> FinanciacionComprador { get; set; }
    }
}
