//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Financiacion_Banco
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Financiacion_Banco()
        {
            this.Financiacion_Simulador = new HashSet<Financiacion_Simulador>();
            this.Financiacion_Solicitud = new HashSet<Financiacion_Solicitud>();
        }
    
        public int IdBanco { get; set; }
        public string Banco { get; set; }
        public string Comercial { get; set; }
        public string Observaciones { get; set; }
        public bool Visible { get; set; }
        public byte EsNuevo { get; set; }
        public byte EsSemiNuevo { get; set; }
        public byte EsOcasion { get; set; }
        public double Importe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Financiacion_Simulador> Financiacion_Simulador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Financiacion_Solicitud> Financiacion_Solicitud { get; set; }
    }
}
