//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Financiacion_Solicitud
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Financiacion_Solicitud()
        {
            this.Alertas = new HashSet<Alertas>();
            this.Financiacion_Solicitud_Fichero = new HashSet<Financiacion_Solicitud_Fichero>();
        }
    
        public int IdSolicitud { get; set; }
        public string NumeroInterno { get; set; }
        public int IdEstado { get; set; }
        public Nullable<System.Guid> IdAfiliado { get; set; }
        public Nullable<System.Guid> IdOperador { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<System.DateTime> FechaFormalizacion { get; set; }
        public bool Firmada { get; set; }
        public string Observaciones { get; set; }
        public string ComentarioInterno { get; set; }
        public Nullable<int> I_IdTipoDocumento { get; set; }
        public string I_NumeroDocumento { get; set; }
        public string I_Nombre { get; set; }
        public string I_Apellido1 { get; set; }
        public string I_Apellido2 { get; set; }
        public Nullable<System.DateTime> I_FechaNacimiento { get; set; }
        public Nullable<int> I_IdPaisNacimiento { get; set; }
        public Nullable<int> I_IdTipoSexo { get; set; }
        public Nullable<int> I_IdEstadoCivil { get; set; }
        public string I_PersonasCargo { get; set; }
        public string I_TelefonoFijo { get; set; }
        public string I_TelefonoMovil { get; set; }
        public string I_Email { get; set; }
        public Nullable<int> I_IdNacionalidad { get; set; }
        public string I_AntiguedadResidente { get; set; }
        public int I_NumeroEmpleos { get; set; }
        public Nullable<int> I_IdTipoTarjeta { get; set; }
        public Nullable<System.DateTime> I_FechaCaducidad { get; set; }
        public string I_FotocopiaDocumento { get; set; }
        public Nullable<int> I_IdTipoDocumento_2 { get; set; }
        public string I_NumeroDocumento_2 { get; set; }
        public string I_Nombre_2 { get; set; }
        public string I_Apellido1_2 { get; set; }
        public string I_Apellido2_2 { get; set; }
        public Nullable<System.DateTime> I_FechaNacimiento_2 { get; set; }
        public Nullable<int> I_IdPaisNacimiento_2 { get; set; }
        public Nullable<int> I_IdTipoSexo_2 { get; set; }
        public Nullable<int> I_IdEstadoCivil_2 { get; set; }
        public string I_PersonasCargo_2 { get; set; }
        public string I_TelefonoFijo_2 { get; set; }
        public string I_TelefonoMovil_2 { get; set; }
        public string I_Email_2 { get; set; }
        public Nullable<int> I_IdNacionalidad_2 { get; set; }
        public string I_AntiguedadResidente_2 { get; set; }
        public int I_NumeroEmpleos_2 { get; set; }
        public Nullable<int> I_IdTipoTarjeta_2 { get; set; }
        public Nullable<System.DateTime> I_FechaCaducidad_2 { get; set; }
        public string I_FotocopiaDocumento_2 { get; set; }
        public Nullable<int> I_IdTipoDocumento_3 { get; set; }
        public string I_NumeroDocumento_3 { get; set; }
        public string I_Nombre_3 { get; set; }
        public string I_Apellido1_3 { get; set; }
        public string I_Apellido2_3 { get; set; }
        public Nullable<System.DateTime> I_FechaNacimiento_3 { get; set; }
        public Nullable<int> I_IdPaisNacimiento_3 { get; set; }
        public Nullable<int> I_IdTipoSexo_3 { get; set; }
        public Nullable<int> I_IdEstadoCivil_3 { get; set; }
        public string I_PersonasCargo_3 { get; set; }
        public string I_TelefonoFijo_3 { get; set; }
        public string I_TelefonoMovil_3 { get; set; }
        public string I_Email_3 { get; set; }
        public Nullable<int> I_IdNacionalidad_3 { get; set; }
        public string I_AntiguedadResidente_3 { get; set; }
        public int I_NumeroEmpleos_3 { get; set; }
        public Nullable<int> I_IdTipoTarjeta_3 { get; set; }
        public Nullable<System.DateTime> I_FechaCaducidad_3 { get; set; }
        public string I_FotocopiaDocumento_3 { get; set; }
        public string I_DatosAdicionales { get; set; }
        public Nullable<int> D_IdTipoVia { get; set; }
        public string D_Direccion { get; set; }
        public string D_Numero { get; set; }
        public string D_Piso { get; set; }
        public string D_CodigoPostal { get; set; }
        public Nullable<int> D_IdLocalidad { get; set; }
        public Nullable<int> D_IdProvincia { get; set; }
        public Nullable<int> D_IdTipoVivienda { get; set; }
        public int D_AnyosAntiguedad { get; set; }
        public int D_MesesAntiguedad { get; set; }
        public Nullable<int> D_IdTipoVia_2 { get; set; }
        public string D_Direccion_2 { get; set; }
        public string D_Numero_2 { get; set; }
        public string D_Piso_2 { get; set; }
        public string D_CodigoPostal_2 { get; set; }
        public Nullable<int> D_IdLocalidad_2 { get; set; }
        public Nullable<int> D_IdProvincia_2 { get; set; }
        public Nullable<int> D_IdTipoVivienda_2 { get; set; }
        public int D_AnyosAntiguedad_2 { get; set; }
        public int D_MesesAntiguedad_2 { get; set; }
        public Nullable<int> D_IdTipoVia_3 { get; set; }
        public string D_Direccion_3 { get; set; }
        public string D_Numero_3 { get; set; }
        public string D_Piso_3 { get; set; }
        public string D_CodigoPostal_3 { get; set; }
        public Nullable<int> D_IdLocalidad_3 { get; set; }
        public Nullable<int> D_IdProvincia_3 { get; set; }
        public Nullable<int> D_IdTipoVivienda_3 { get; set; }
        public int D_AnyosAntiguedad_3 { get; set; }
        public int D_MesesAntiguedad_3 { get; set; }
        public Nullable<int> P_IdSituacionProfesional { get; set; }
        public Nullable<System.DateTime> P_FechaAltaSS { get; set; }
        public Nullable<int> P_IdTipoIngreso { get; set; }
        public double P_Ingresos { get; set; }
        public string P_NombreEmpresa { get; set; }
        public int P_AnyosAntiguedad { get; set; }
        public int P_MesesAntiguedad { get; set; }
        public Nullable<int> P_IdTipoEmpleo { get; set; }
        public Nullable<int> P_IdCargo { get; set; }
        public string P_TelefonoEmpresa { get; set; }
        public string P_Nomina1 { get; set; }
        public string P_Nomina2 { get; set; }
        public Nullable<int> P_IdSituacionProfesional_2 { get; set; }
        public Nullable<System.DateTime> P_FechaAltaSS_2 { get; set; }
        public Nullable<int> P_IdTipoIngreso_2 { get; set; }
        public double P_Ingresos_2 { get; set; }
        public string P_NombreEmpresa_2 { get; set; }
        public int P_AnyosAntiguedad_2 { get; set; }
        public int P_MesesAntiguedad_2 { get; set; }
        public Nullable<int> P_IdTipoEmpleo_2 { get; set; }
        public Nullable<int> P_IdCargo_2 { get; set; }
        public string P_TelefonoEmpresa_2 { get; set; }
        public Nullable<int> P_IdSituacionProfesional_3 { get; set; }
        public string P_Nomina1_2 { get; set; }
        public string P_Nomina2_2 { get; set; }
        public Nullable<System.DateTime> P_FechaAltaSS_3 { get; set; }
        public Nullable<int> P_IdTipoIngreso_3 { get; set; }
        public double P_Ingresos_3 { get; set; }
        public string P_NombreEmpresa_3 { get; set; }
        public int P_AnyosAntiguedad_3 { get; set; }
        public int P_MesesAntiguedad_3 { get; set; }
        public Nullable<int> P_IdTipoEmpleo_3 { get; set; }
        public Nullable<int> P_IdCargo_3 { get; set; }
        public string P_TelefonoEmpresa_3 { get; set; }
        public string P_Nomina1_3 { get; set; }
        public string P_Nomina2_3 { get; set; }
        public string V_IdTVehiculo { get; set; }
        public string V_IdTMarca { get; set; }
        public Nullable<int> V_IdTModelo { get; set; }
        public string V_Combustible { get; set; }
        public string V_Carroceria { get; set; }
        public Nullable<int> V_Antiguedad { get; set; }
        public Nullable<int> V_IdTVersion { get; set; }
        public Nullable<System.DateTime> V_FechaMatriculacion { get; set; }
        public string V_Matricula { get; set; }
        public string V_NumeroChasis { get; set; }
        public string V_FichaTecnica { get; set; }
        public string V_PermisoCirculacion { get; set; }
        public double C_PVP { get; set; }
        public double C_ImporteFinanciar { get; set; }
        public Nullable<int> C_IdPlazo { get; set; }
        public Nullable<int> C_IdFPagoGasto { get; set; }
        public Nullable<int> C_IdFPagoSeguro { get; set; }
        public double C_Cuota { get; set; }
        public Nullable<int> C_IdBanco { get; set; }
        public string C_TitularCuenta { get; set; }
        public string C_IBAN { get; set; }
        public string C_Cartilla { get; set; }
        public double C_Entrada { get; set; }
        public double C_TIN { get; set; }
        public double C_Interes { get; set; }
        public double C_Apertura { get; set; }
        public double C_PrimerPago { get; set; }
        public double C_PagoMensual { get; set; }
        public double C_PagoTotal { get; set; }
        public string ComTexto { get; set; }
        public Nullable<bool> Leido { get; set; }
        public double Comision_Imp { get; set; }
        public double Comision_Por { get; set; }
        public string V_PermisoCirculacion2 { get; set; }
        public string E_NombreNotario { get; set; }
        public string E_NumProtocolo { get; set; }
        public string E_Folio { get; set; }
        public string E_Tomo { get; set; }
        public string E_Hoja { get; set; }
        public string E_Inscripcion { get; set; }
        public string E_ImpuestoSociedades { get; set; }
        public string E_ObjetoSocial { get; set; }
        public string E_Telefono { get; set; }
        public byte EstadoPreSolicitud { get; set; }
        public bool Visible { get; set; }
        public Nullable<int> C_IdPlazoCompleto { get; set; }
        public Nullable<int> NumeroOperacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alertas> Alertas { get; set; }
        public virtual Financiacion_Banco Financiacion_Banco { get; set; }
        public virtual Financiacion_Cargo Financiacion_Cargo { get; set; }
        public virtual Financiacion_Cargo Financiacion_Cargo1 { get; set; }
        public virtual Financiacion_Cargo Financiacion_Cargo2 { get; set; }
        public virtual Financiacion_Estado Financiacion_Estado { get; set; }
        public virtual Financiacion_EstadoCivil Financiacion_EstadoCivil { get; set; }
        public virtual Financiacion_EstadoCivil Financiacion_EstadoCivil1 { get; set; }
        public virtual Financiacion_EstadoCivil Financiacion_EstadoCivil2 { get; set; }
        public virtual Financiacion_FormaPago Financiacion_FormaPago { get; set; }
        public virtual Financiacion_FormaPago Financiacion_FormaPago1 { get; set; }
        public virtual Financiacion_PlazoMeses Financiacion_PlazoMeses { get; set; }
        public virtual Financiacion_SituacionProfesional Financiacion_SituacionProfesional { get; set; }
        public virtual Financiacion_SituacionProfesional Financiacion_SituacionProfesional1 { get; set; }
        public virtual Financiacion_SituacionProfesional Financiacion_SituacionProfesional2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Financiacion_Solicitud_Fichero> Financiacion_Solicitud_Fichero { get; set; }
        public virtual Financiacion_TipoDocumento Financiacion_TipoDocumento { get; set; }
        public virtual Financiacion_TipoDocumento Financiacion_TipoDocumento1 { get; set; }
        public virtual Financiacion_TipoDocumento Financiacion_TipoDocumento2 { get; set; }
        public virtual Financiacion_TipoEmpleo Financiacion_TipoEmpleo { get; set; }
        public virtual Financiacion_TipoEmpleo Financiacion_TipoEmpleo1 { get; set; }
        public virtual Financiacion_TipoEmpleo Financiacion_TipoEmpleo2 { get; set; }
        public virtual Financiacion_TipoIngreso Financiacion_TipoIngreso { get; set; }
        public virtual Financiacion_TipoIngreso Financiacion_TipoIngreso1 { get; set; }
        public virtual Financiacion_TipoIngreso Financiacion_TipoIngreso2 { get; set; }
        public virtual Financiacion_TipoSexo Financiacion_TipoSexo { get; set; }
        public virtual Financiacion_TipoSexo Financiacion_TipoSexo1 { get; set; }
        public virtual Financiacion_TipoSexo Financiacion_TipoSexo2 { get; set; }
        public virtual Financiacion_TipoTarjeta Financiacion_TipoTarjeta { get; set; }
        public virtual Financiacion_TipoTarjeta Financiacion_TipoTarjeta1 { get; set; }
        public virtual Financiacion_TipoTarjeta Financiacion_TipoTarjeta2 { get; set; }
        public virtual Financiacion_TipoVia Financiacion_TipoVia { get; set; }
        public virtual Financiacion_TipoVia Financiacion_TipoVia1 { get; set; }
        public virtual Financiacion_TipoVia Financiacion_TipoVia2 { get; set; }
        public virtual Financiacion_TipoVivienda Financiacion_TipoVivienda { get; set; }
        public virtual Financiacion_TipoVivienda Financiacion_TipoVivienda1 { get; set; }
        public virtual Financiacion_TipoVivienda Financiacion_TipoVivienda2 { get; set; }
        public virtual Munincipios Munincipios { get; set; }
        public virtual Munincipios Munincipios1 { get; set; }
        public virtual Munincipios Munincipios2 { get; set; }
        public virtual Pais Pais { get; set; }
        public virtual Pais Pais1 { get; set; }
        public virtual Pais Pais2 { get; set; }
        public virtual Pais Pais3 { get; set; }
        public virtual Pais Pais4 { get; set; }
        public virtual Pais Pais5 { get; set; }
        public virtual Provincias Provincias { get; set; }
        public virtual Provincias Provincias1 { get; set; }
        public virtual Provincias Provincias2 { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
    }
}
