//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinanciacionComprador
    {
        public int ID { get; set; }
        public Nullable<int> FinanciacionID { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string DNI { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string EstadoCivil { get; set; }
        public string Direccion { get; set; }
        public string CP { get; set; }
        public Nullable<int> ProvinciaID { get; set; }
        public Nullable<int> LocalidadID { get; set; }
        public string Nacionalidad { get; set; }
        public Nullable<System.DateTime> VtoResidencia { get; set; }
        public Nullable<int> PersonasACargo { get; set; }
        public string Telefono { get; set; }
        public string Movil { get; set; }
        public string TipoContrato { get; set; }
        public string Profesion { get; set; }
        public string Empresa { get; set; }
        public string DireccionEmpresa { get; set; }
        public string CPEmpresa { get; set; }
        public Nullable<int> ProvinciaIDEmpresa { get; set; }
        public Nullable<int> LocalidadIDEmpresa { get; set; }
        public string TelefonoEmpresa { get; set; }
        public Nullable<System.DateTime> Antiguedad { get; set; }
        public Nullable<decimal> IngresosFijos { get; set; }
        public Nullable<decimal> OtrosIngresos { get; set; }
        public string TipoVivienda { get; set; }
        public Nullable<int> ValorVivienda { get; set; }
        public Nullable<decimal> MensualidadHipoteca { get; set; }
        public Nullable<decimal> MensualidadAlquiler { get; set; }
    
        public virtual Financiacion Financiacion { get; set; }
        public virtual Munincipios Munincipios { get; set; }
        public virtual Provincias Provincias { get; set; }
    }
}
