//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformesTraficoLin
    {
        public int IdInformesTraficoLin { get; set; }
        public int IdInformesTraficoCab { get; set; }
        public string Matricula { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
        public Nullable<int> IdSaldoServiciosLin { get; set; }
        public byte[] InformePDF { get; set; }
        public string NombreArchivo { get; set; }
        public Nullable<int> LongitudArchivo { get; set; }
        public Nullable<int> IdEtiquetasDGT { get; set; }
        public Nullable<int> Estado { get; set; }
    }
}
