//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Juridico_Consultas
    {
        public int Id { get; set; }
        public string NumeroConsulta { get; set; }
        public string Descripcion { get; set; }
        public string Contestacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaRevision { get; set; }
        public Nullable<System.DateTime> FechaRespuesta { get; set; }
        public string Serie { get; set; }
        public Nullable<int> Estado { get; set; }
        public System.Guid IdAfiliado { get; set; }
        public string NombreFichero { get; set; }
        public string URLFichero { get; set; }
        public string EstadoDescrip { get; set; }
    }
}
