//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class listados
    {
        public int id_listado { get; set; }
        public string nombre { get; set; }
        public string tipo { get; set; }
        public string camposVisibles { get; set; }
        public string plantilla { get; set; }
        public string filtro { get; set; }
        public Nullable<int> tipoFiltro { get; set; }
        public string query { get; set; }
    }
}
