//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matriculas_Antiguas
    {
        public int ID { get; set; }
        public string Provincia { get; set; }
        public Nullable<int> idProvincia { get; set; }
        public string Numero { get; set; }
        public string Letra { get; set; }
        public Nullable<int> Dia { get; set; }
        public Nullable<int> Mes { get; set; }
        public string Anyo { get; set; }
        public string Bastidor { get; set; }
        public string Matricula { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
    }
}
