//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matriculas_Clasicas
    {
        public int ID { get; set; }
        public string Provincia { get; set; }
        public Nullable<int> idProvincia { get; set; }
        public Nullable<int> Numero { get; set; }
        public string Dia { get; set; }
        public string Mes { get; set; }
        public string Anyo { get; set; }
    }
}
