//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class qcu947Entities2 : DbContext
    {
        public qcu947Entities2()
            : base("name=qcu947Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<A_AAnarByStatus> A_AAnarByStatus { get; set; }
        public virtual DbSet<A_AnarByRoute> A_AnarByRoute { get; set; }
        public virtual DbSet<A_DT> A_DT { get; set; }
        public virtual DbSet<A_Hours> A_Hours { get; set; }
        public virtual DbSet<A_Lines> A_Lines { get; set; }
        public virtual DbSet<A_Routes> A_Routes { get; set; }
        public virtual DbSet<A_Stopper> A_Stopper { get; set; }
        public virtual DbSet<A_Temp> A_Temp { get; set; }
        public virtual DbSet<A_Traces> A_Traces { get; set; }
        public virtual DbSet<Agenda> Agenda { get; set; }
        public virtual DbSet<AH_Terrassa_schedule> AH_Terrassa_schedule { get; set; }
        public virtual DbSet<Alertas> Alertas { get; set; }
        public virtual DbSet<AnarBy_TerresaRealTime> AnarBy_TerresaRealTime { get; set; }
        public virtual DbSet<AnuncioCoches> AnuncioCoches { get; set; }
        public virtual DbSet<AnuncioCochesExtra> AnuncioCochesExtra { get; set; }
        public virtual DbSet<Anuncios> Anuncios { get; set; }
        public virtual DbSet<AnuncioTipo> AnuncioTipo { get; set; }
        public virtual DbSet<Apoyos> Apoyos { get; set; }
        public virtual DbSet<aspnet_Applications> aspnet_Applications { get; set; }
        public virtual DbSet<aspnet_Paths> aspnet_Paths { get; set; }
        public virtual DbSet<AspNet_SqlCacheTablesForChangeNotification> AspNet_SqlCacheTablesForChangeNotification { get; set; }
        public virtual DbSet<BancoMaster> BancoMaster { get; set; }
        public virtual DbSet<Boletines> Boletines { get; set; }
        public virtual DbSet<BoletinesNoticias> BoletinesNoticias { get; set; }
        public virtual DbSet<Canasta> Canasta { get; set; }
        public virtual DbSet<CategoriaImagenes> CategoriaImagenes { get; set; }
        public virtual DbSet<Categorias> Categorias { get; set; }
        public virtual DbSet<CategoriasDocumentos> CategoriasDocumentos { get; set; }
        public virtual DbSet<CategoriasEnlaces> CategoriasEnlaces { get; set; }
        public virtual DbSet<CategoriasRoles> CategoriasRoles { get; set; }
        public virtual DbSet<CategoriaTienda> CategoriaTienda { get; set; }
        public virtual DbSet<ClientesFinanciacion> ClientesFinanciacion { get; set; }
        public virtual DbSet<CochesRobados> CochesRobados { get; set; }
        public virtual DbSet<Comunidad> Comunidad { get; set; }
        public virtual DbSet<ConductoresPoliza> ConductoresPoliza { get; set; }
        public virtual DbSet<ConductorSeguroFlotante> ConductorSeguroFlotante { get; set; }
        public virtual DbSet<Departamentos> Departamentos { get; set; }
        public virtual DbSet<DepartamentosServicios> DepartamentosServicios { get; set; }
        public virtual DbSet<DerechoRealPorcientos> DerechoRealPorcientos { get; set; }
        public virtual DbSet<DerechosReales2016> DerechosReales2016 { get; set; }
        public virtual DbSet<DerechosReales2017> DerechosReales2017 { get; set; }
        public virtual DbSet<DerechosReales2018> DerechosReales2018 { get; set; }
        public virtual DbSet<Diarios> Diarios { get; set; }
        public virtual DbSet<Documentos> Documentos { get; set; }
        public virtual DbSet<DocumentosReclamacion> DocumentosReclamacion { get; set; }
        public virtual DbSet<EmailsEnvioBoletin> EmailsEnvioBoletin { get; set; }
        public virtual DbSet<Empresas> Empresas { get; set; }
        public virtual DbSet<EmpresasColaboradoras> EmpresasColaboradoras { get; set; }
        public virtual DbSet<Enlaces> Enlaces { get; set; }
        public virtual DbSet<Errors> Errors { get; set; }
        public virtual DbSet<Est_Log> Est_Log { get; set; }
        public virtual DbSet<EstadisticasVNMensualesTemp> EstadisticasVNMensualesTemp { get; set; }
        public virtual DbSet<EstadisticasVNSemanalesTemp> EstadisticasVNSemanalesTemp { get; set; }
        public virtual DbSet<EstadisticasVNTotalesTemp> EstadisticasVNTotalesTemp { get; set; }
        public virtual DbSet<EtiquetasDGT> EtiquetasDGT { get; set; }
        public virtual DbSet<Facturacion> Facturacion { get; set; }
        public virtual DbSet<FacturacionEstadoFichDevuelto> FacturacionEstadoFichDevuelto { get; set; }
        public virtual DbSet<FacturacionFichRecDevueltos> FacturacionFichRecDevueltos { get; set; }
        public virtual DbSet<FacturacionRemesaEstado> FacturacionRemesaEstado { get; set; }
        public virtual DbSet<FacturaDetalle> FacturaDetalle { get; set; }
        public virtual DbSet<FacturaGlobal> FacturaGlobal { get; set; }
        public virtual DbSet<FacturaServicio> FacturaServicio { get; set; }
        public virtual DbSet<Financiacion> Financiacion { get; set; }
        public virtual DbSet<Financiacion_Banco> Financiacion_Banco { get; set; }
        public virtual DbSet<Financiacion_Cargo> Financiacion_Cargo { get; set; }
        public virtual DbSet<Financiacion_CondicionVehiculo> Financiacion_CondicionVehiculo { get; set; }
        public virtual DbSet<Financiacion_Configuracion> Financiacion_Configuracion { get; set; }
        public virtual DbSet<Financiacion_Consultas> Financiacion_Consultas { get; set; }
        public virtual DbSet<Financiacion_Estado> Financiacion_Estado { get; set; }
        public virtual DbSet<Financiacion_EstadoCivil> Financiacion_EstadoCivil { get; set; }
        public virtual DbSet<Financiacion_FormaPago> Financiacion_FormaPago { get; set; }
        public virtual DbSet<Financiacion_OLD> Financiacion_OLD { get; set; }
        public virtual DbSet<Financiacion_PlazoMeses> Financiacion_PlazoMeses { get; set; }
        public virtual DbSet<Financiacion_Simulador> Financiacion_Simulador { get; set; }
        public virtual DbSet<Financiacion_SituacionProfesional> Financiacion_SituacionProfesional { get; set; }
        public virtual DbSet<Financiacion_Solicitud> Financiacion_Solicitud { get; set; }
        public virtual DbSet<Financiacion_Solicitud_Fichero> Financiacion_Solicitud_Fichero { get; set; }
        public virtual DbSet<Financiacion_TipoDocumento> Financiacion_TipoDocumento { get; set; }
        public virtual DbSet<Financiacion_TipoEmpleo> Financiacion_TipoEmpleo { get; set; }
        public virtual DbSet<Financiacion_TipoIngreso> Financiacion_TipoIngreso { get; set; }
        public virtual DbSet<Financiacion_TipoSexo> Financiacion_TipoSexo { get; set; }
        public virtual DbSet<Financiacion_TipoTarjeta> Financiacion_TipoTarjeta { get; set; }
        public virtual DbSet<Financiacion_TipoVia> Financiacion_TipoVia { get; set; }
        public virtual DbSet<Financiacion_TipoVivienda> Financiacion_TipoVivienda { get; set; }
        public virtual DbSet<Financiacion_Usuario_Banco> Financiacion_Usuario_Banco { get; set; }
        public virtual DbSet<Financiacion_Usuario_Datos> Financiacion_Usuario_Datos { get; set; }
        public virtual DbSet<FinanciacionBanco> FinanciacionBanco { get; set; }
        public virtual DbSet<FinanciacionComprador> FinanciacionComprador { get; set; }
        public virtual DbSet<FinanciacionEntidad_DELETE> FinanciacionEntidad_DELETE { get; set; }
        public virtual DbSet<FinanciacionEstado> FinanciacionEstado { get; set; }
        public virtual DbSet<HomeEnlaces> HomeEnlaces { get; set; }
        public virtual DbSet<Idiomas> Idiomas { get; set; }
        public virtual DbSet<Imagenes> Imagenes { get; set; }
        public virtual DbSet<ImagenesNoticias> ImagenesNoticias { get; set; }
        public virtual DbSet<InformesTraficoCab> InformesTraficoCab { get; set; }
        public virtual DbSet<InformesTraficoLin> InformesTraficoLin { get; set; }
        public virtual DbSet<Juridico_Consultas> Juridico_Consultas { get; set; }
        public virtual DbSet<Juridico_Estados> Juridico_Estados { get; set; }
        public virtual DbSet<Juridico_Niveles> Juridico_Niveles { get; set; }
        public virtual DbSet<Juridico_TopTen> Juridico_TopTen { get; set; }
        public virtual DbSet<listados> listados { get; set; }
        public virtual DbSet<MarcasCoche> MarcasCoche { get; set; }
        public virtual DbSet<MatriculaPoliza> MatriculaPoliza { get; set; }
        public virtual DbSet<Matriculas_Actuales> Matriculas_Actuales { get; set; }
        public virtual DbSet<Matriculas_Antiguas> Matriculas_Antiguas { get; set; }
        public virtual DbSet<Matriculas_Ciclomotores> Matriculas_Ciclomotores { get; set; }
        public virtual DbSet<Matriculas_Clasicas> Matriculas_Clasicas { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<Messages> Messages { get; set; }
        public virtual DbSet<ModelosCoches> ModelosCoches { get; set; }
        public virtual DbSet<Munincipios> Munincipios { get; set; }
        public virtual DbSet<Noticias> Noticias { get; set; }
        public virtual DbSet<NoticiasAncove> NoticiasAncove { get; set; }
        public virtual DbSet<NoticiasOficiales> NoticiasOficiales { get; set; }
        public virtual DbSet<Numeradores> Numeradores { get; set; }
        public virtual DbSet<NumeradoresCab> NumeradoresCab { get; set; }
        public virtual DbSet<NumeradoresLin> NumeradoresLin { get; set; }
        public virtual DbSet<PagoTPV> PagoTPV { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<Pedidos> Pedidos { get; set; }
        public virtual DbSet<PedidosDetalle> PedidosDetalle { get; set; }
        public virtual DbSet<Peritaciones> Peritaciones { get; set; }
        public virtual DbSet<Peritaciones_Estados> Peritaciones_Estados { get; set; }
        public virtual DbSet<Peritaciones_Ficheros> Peritaciones_Ficheros { get; set; }
        public virtual DbSet<Peritaciones_Guardadas> Peritaciones_Guardadas { get; set; }
        public virtual DbSet<Peritaciones_Informes> Peritaciones_Informes { get; set; }
        public virtual DbSet<Peritaciones_PagoTPV> Peritaciones_PagoTPV { get; set; }
        public virtual DbSet<Portal> Portal { get; set; }
        public virtual DbSet<Provincias> Provincias { get; set; }
        public virtual DbSet<Prueba> Prueba { get; set; }
        public virtual DbSet<Publicaciones> Publicaciones { get; set; }
        public virtual DbSet<Publicador> Publicador { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<RolesTipo> RolesTipo { get; set; }
        public virtual DbSet<SaldoServiciosCab> SaldoServiciosCab { get; set; }
        public virtual DbSet<SaldoServiciosLin> SaldoServiciosLin { get; set; }
        public virtual DbSet<SchedelulesTrain> SchedelulesTrain { get; set; }
        public virtual DbSet<SeguroFlotante> SeguroFlotante { get; set; }
        public virtual DbSet<SiteConfig> SiteConfig { get; set; }
        public virtual DbSet<SiteTranslation> SiteTranslation { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tienda> Tienda { get; set; }
        public virtual DbSet<TipoCombustible> TipoCombustible { get; set; }
        public virtual DbSet<TipoConductorSeguroFlotante> TipoConductorSeguroFlotante { get; set; }
        public virtual DbSet<TipoEstablecimiento> TipoEstablecimiento { get; set; }
        public virtual DbSet<TipoFacturaServicio> TipoFacturaServicio { get; set; }
        public virtual DbSet<TipoIva> TipoIva { get; set; }
        public virtual DbSet<TipoUsuario> TipoUsuario { get; set; }
        public virtual DbSet<TPV> TPV { get; set; }
        public virtual DbSet<Transporte_Agenda> Transporte_Agenda { get; set; }
        public virtual DbSet<Transporte_Baleares> Transporte_Baleares { get; set; }
        public virtual DbSet<Transporte_Canarias> Transporte_Canarias { get; set; }
        public virtual DbSet<Transporte_Coeficiente> Transporte_Coeficiente { get; set; }
        public virtual DbSet<Transporte_Estados> Transporte_Estados { get; set; }
        public virtual DbSet<Transporte_Localidades> Transporte_Localidades { get; set; }
        public virtual DbSet<Transporte_Message> Transporte_Message { get; set; }
        public virtual DbSet<Transporte_Observaciones> Transporte_Observaciones { get; set; }
        public virtual DbSet<Transporte_PagoTPV> Transporte_PagoTPV { get; set; }
        public virtual DbSet<Transporte_Ponderada> Transporte_Ponderada { get; set; }
        public virtual DbSet<Transporte_Referencia> Transporte_Referencia { get; set; }
        public virtual DbSet<Transporte_SeguimientoManual> Transporte_SeguimientoManual { get; set; }
        public virtual DbSet<Transporte_Tipo> Transporte_Tipo { get; set; }
        public virtual DbSet<Transporte_Transportista> Transporte_Transportista { get; set; }
        public virtual DbSet<TransporteCab> TransporteCab { get; set; }
        public virtual DbSet<TransporteLin> TransporteLin { get; set; }
        public virtual DbSet<TransportePedidosCab> TransportePedidosCab { get; set; }
        public virtual DbSet<TransportePedidosLin> TransportePedidosLin { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UsersInRoles> UsersInRoles { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<UsuariosAvisos> UsuariosAvisos { get; set; }
        public virtual DbSet<UsuariosBoletines> UsuariosBoletines { get; set; }
        public virtual DbSet<UsuariosDatosBancarios> UsuariosDatosBancarios { get; set; }
        public virtual DbSet<UsuariosEstado> UsuariosEstado { get; set; }
        public virtual DbSet<UsuariosServicios> UsuariosServicios { get; set; }
        public virtual DbSet<UsuariosServiciosFacturados> UsuariosServiciosFacturados { get; set; }
        public virtual DbSet<UsuariosServiciosSeguimiento> UsuariosServiciosSeguimiento { get; set; }
        public virtual DbSet<VehiculoSeguroFlotante> VehiculoSeguroFlotante { get; set; }
        public virtual DbSet<C_botigues> C_botigues { get; set; }
        public virtual DbSet<C_Fantasmas> C_Fantasmas { get; set; }
        public virtual DbSet<AlertasAfiliados> AlertasAfiliados { get; set; }
        public virtual DbSet<botigues> botigues { get; set; }
        public virtual DbSet<ClientesFinanciacion_bak> ClientesFinanciacion_bak { get; set; }
        public virtual DbSet<clients> clients { get; set; }
        public virtual DbSet<Consulta_etiquetes_A> Consulta_etiquetes_A { get; set; }
        public virtual DbSet<Consulta_etiquetes_B> Consulta_etiquetes_B { get; set; }
        public virtual DbSet<Consulta_fitxa_associats> Consulta_fitxa_associats { get; set; }
        public virtual DbSet<consulta_sobres_botigues> consulta_sobres_botigues { get; set; }
        public virtual DbSet<DerechosReales> DerechosReales { get; set; }
        public virtual DbSet<DerechosReales2019> DerechosReales2019 { get; set; }
        public virtual DbSet<DerechosReales2020> DerechosReales2020 { get; set; }
        public virtual DbSet<Financiacion_PlazoMesesCompleto> Financiacion_PlazoMesesCompleto { get; set; }
        public virtual DbSet<Juridico_Contenido> Juridico_Contenido { get; set; }
        public virtual DbSet<Juridico_Temas> Juridico_Temas { get; set; }
        public virtual DbSet<Juridico_Titulos> Juridico_Titulos { get; set; }
        public virtual DbSet<MessageRecipients> MessageRecipients { get; set; }
        public virtual DbSet<Municipios_Mapa> Municipios_Mapa { get; set; }
        public virtual DbSet<NumeradorTemporalFacturas> NumeradorTemporalFacturas { get; set; }
        public virtual DbSet<Peritaciones_Km> Peritaciones_Km { get; set; }
        public virtual DbSet<Peritaciones_Talleres> Peritaciones_Talleres { get; set; }
        public virtual DbSet<Peritaciones_Tarifas> Peritaciones_Tarifas { get; set; }
        public virtual DbSet<Peritos_Poblacion> Peritos_Poblacion { get; set; }
        public virtual DbSet<t_clients> t_clients { get; set; }
        public virtual DbSet<t_clients1> t_clients1 { get; set; }
    }
}
