//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoticiasOficiales
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaPublicacion { get; set; }
        public Nullable<System.DateTime> FechaCaducidad { get; set; }
        public Nullable<System.Guid> Usuario { get; set; }
        public string PathRecurso { get; set; }
        public string NombreFichero { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> ProvinciaID { get; set; }
        public Nullable<int> ComunidadID { get; set; }
        public Nullable<int> PublicadorID { get; set; }
    
        public virtual Comunidad Comunidad { get; set; }
        public virtual Provincias Provincias { get; set; }
        public virtual Publicador Publicador { get; set; }
    }
}
