//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoticiasAncove
    {
        public int Id { get; set; }
        public string ExtId { get; set; }
        public string Titulo { get; set; }
        public string UrlTitulo { get; set; }
        public string Entrada { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaPublicacion { get; set; }
        public Nullable<System.DateTime> FechaCaducidad { get; set; }
        public string Web { get; set; }
        public bool Destacado { get; set; }
        public Nullable<int> Orden { get; set; }
        public Nullable<int> Departamento { get; set; }
        public int Portal { get; set; }
        public Nullable<int> Territorio { get; set; }
        public Nullable<short> Ambito { get; set; }
        public Nullable<System.Guid> Usuario { get; set; }
        public string Imagen { get; set; }
        public Nullable<int> CantidadImagen { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public int OrigenRSS { get; set; }
        public string NewURL { get; set; }
        public string ShortURL { get; set; }
    
        public virtual Departamentos Departamentos { get; set; }
    }
}
