//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NumeradoresLin
    {
        public int IdNumeradoresLin { get; set; }
        public int IdNumeradoresCab { get; set; }
        public decimal Year { get; set; }
        public string Serie { get; set; }
        public int NumeradorC { get; set; }
        public int NumeradorA { get; set; }
        public bool Estado { get; set; }
        public string HojaEstilo { get; set; }
        public bool EsFactura { get; set; }
    
        public virtual NumeradoresCab NumeradoresCab { get; set; }
    }
}
