//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NumeradorTemporalFacturas
    {
        public int id { get; set; }
        public int IdNumeradorLin { get; set; }
        public string SerieFactura { get; set; }
        public string TipoFactura { get; set; }
        public Nullable<int> IdFactura { get; set; }
    }
}
