//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagoTPV
    {
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public System.Guid IdUsuario { get; set; }
        public double Total { get; set; }
        public double ImporteIva { get; set; }
        public int Cantidad { get; set; }
        public string Matriculas { get; set; }
        public string Observaciones { get; set; }
        public string NumeroPedido { get; set; }
        public string Origen { get; set; }
    }
}
