//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pais
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pais()
        {
            this.Financiacion_Solicitud = new HashSet<Financiacion_Solicitud>();
            this.Financiacion_Solicitud1 = new HashSet<Financiacion_Solicitud>();
            this.Financiacion_Solicitud2 = new HashSet<Financiacion_Solicitud>();
            this.Financiacion_Solicitud3 = new HashSet<Financiacion_Solicitud>();
            this.Financiacion_Solicitud4 = new HashSet<Financiacion_Solicitud>();
            this.Financiacion_Solicitud5 = new HashSet<Financiacion_Solicitud>();
        }
    
        public int IdPais { get; set; }
        public string Pais1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Financiacion_Solicitud> Financiacion_Solicitud { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Financiacion_Solicitud> Financiacion_Solicitud1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Financiacion_Solicitud> Financiacion_Solicitud2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Financiacion_Solicitud> Financiacion_Solicitud3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Financiacion_Solicitud> Financiacion_Solicitud4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Financiacion_Solicitud> Financiacion_Solicitud5 { get; set; }
    }
}
