//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Peritaciones_Guardadas
    {
        public int IdPeritacion { get; set; }
        public string TipoDePeritacion { get; set; }
        public decimal PrecioTipoDePeritacion { get; set; }
        public string Valoracion { get; set; }
        public decimal PrecioValoracion { get; set; }
        public string TipoDeVehiculo { get; set; }
        public short Extra_InformeJudicial { get; set; }
        public decimal PrecioExtra_InformeJuicio { get; set; }
        public short Extra_AsistenciaJuicio { get; set; }
        public decimal PrecioExtra_AsistenciaJuicio { get; set; }
        public decimal PrecioKm { get; set; }
        public string Matricula { get; set; }
        public int KmVehiculo { get; set; }
        public string IdTVehiculo { get; set; }
        public string IdTMarca { get; set; }
        public int IdTModelo { get; set; }
        public System.DateTime Fecha1aMatriculacion { get; set; }
        public string NombreTaller { get; set; }
        public int IdProvincia { get; set; }
        public int IdPoblacion { get; set; }
        public string CP { get; set; }
        public string Direccion { get; set; }
        public string ContactoTaller { get; set; }
        public string TelefonoTaller { get; set; }
        public System.DateTime FechaEntradaTaller { get; set; }
        public System.DateTime DiaPeritacion { get; set; }
        public string Motivo { get; set; }
        public string Observaciones { get; set; }
        public System.Guid IDAFILIADO { get; set; }
        public decimal KmDesplazamientoPerito { get; set; }
        public string NumExpediente { get; set; }
        public string DatosSiniestro { get; set; }
        public string Modelo { get; set; }
    }
}
