//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Peritaciones_Tarifas
    {
        public int Id { get; set; }
        public decimal P_TipoPeritacionDanosMecanicos { get; set; }
        public decimal P_TipoPeritacionDanosCarroceria { get; set; }
        public decimal P_SinValoracion { get; set; }
        public decimal P_ConValoracion { get; set; }
        public decimal Extra_InformeJuicio { get; set; }
        public decimal Extra_AsistenciaJuicio { get; set; }
        public decimal PrecioKm { get; set; }
        public string TipoVehiculo { get; set; }
        public decimal P_TipoPeritacionDanosMecanicos_INVARAT { get; set; }
        public decimal P_TipoPeritacionDanosCarroceria_INVARAT { get; set; }
        public decimal P_SinValoracion_INVARAT { get; set; }
        public decimal P_ConValoracion_INVARAT { get; set; }
        public decimal Extra_InformeJuicio_INVARAT { get; set; }
        public decimal Extra_AsistenciaJuicio_INVARAT { get; set; }
        public decimal PrecioKm_INVARAT { get; set; }
        public Nullable<decimal> AusenciaVisitaPerito { get; set; }
        public short cobrarPenalizacion { get; set; }
    }
}
