//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Peritaciones_PagoTPV
    {
        public int IdPeritacionPago { get; set; }
        public string TipoDePeritacion { get; set; }
        public Nullable<decimal> PrecioTipoDePeritacion { get; set; }
        public string TipoDeVehiculo { get; set; }
        public Nullable<decimal> PrecioExtra_AsistenciaJuicio { get; set; }
        public Nullable<decimal> PrecioKm { get; set; }
        public string Matricula { get; set; }
        public Nullable<int> KmVehiculo { get; set; }
        public string IdTVehiculo { get; set; }
        public string IdTMarca { get; set; }
        public Nullable<int> IdTModelo { get; set; }
        public string Modelo { get; set; }
        public Nullable<System.DateTime> Fecha1aMatriculacion { get; set; }
        public string NombreTaller { get; set; }
        public Nullable<int> IdProvincia { get; set; }
        public Nullable<int> IdPoblacion { get; set; }
        public string CP { get; set; }
        public string Direccion { get; set; }
        public string ContactoTaller { get; set; }
        public string TelefonoTaller { get; set; }
        public Nullable<System.DateTime> FechaEntradaTaller { get; set; }
        public Nullable<System.DateTime> DiaPeritacion { get; set; }
        public string Motivo { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.Guid> IDAFILIADO { get; set; }
        public Nullable<decimal> KmDesplazamientoPerito { get; set; }
        public Nullable<int> TipoServicio { get; set; }
        public string Concepto { get; set; }
        public string IdTPV { get; set; }
        public Nullable<short> Extra_AsistenciaJuicio { get; set; }
        public Nullable<int> IdPeritacion { get; set; }
        public Nullable<decimal> PrecioAusencia { get; set; }
    }
}
