//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publicaciones
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Entrada { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaPublicacion { get; set; }
        public System.DateTime FechaCaducidad { get; set; }
        public Nullable<System.Guid> Usuario { get; set; }
        public int Departamento { get; set; }
        public int Portal { get; set; }
        public string PathRecurso { get; set; }
        public string Imagen { get; set; }
        public Nullable<int> CantidadImagen { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string NombreFichero { get; set; }
    }
}
