//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolesTipo
    {
        public string TipoRol { get; set; }
        public string RoleName { get; set; }
        public bool ver { get; set; }
        public bool modificar { get; set; }
        public bool borrar { get; set; }
        public byte nivel { get; set; }
    }
}
