//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeguroFlotante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SeguroFlotante()
        {
            this.VehiculoSeguroFlotante = new HashSet<VehiculoSeguroFlotante>();
        }
    
        public Nullable<System.Guid> Id_borrar { get; set; }
        public string NombreTomador { get; set; }
        public string DireccionTomador { get; set; }
        public string CodPostalTomador { get; set; }
        public string LocalidadTomador { get; set; }
        public string ProvinciaTomador { get; set; }
        public string NIFCIFTomador { get; set; }
        public string EmailTomador { get; set; }
        public string CuentaBancariaTomador { get; set; }
        public System.DateTime FechaEfecto { get; set; }
        public int Estado { get; set; }
        public int Id { get; set; }
        public string TelefonoTomador { get; set; }
        public string FaxTomador { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehiculoSeguroFlotante> VehiculoSeguroFlotante { get; set; }
    }
}
