//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPV
    {
        public int ID { get; set; }
        public string DS_Date { get; set; }
        public string DS_Hour { get; set; }
        public string DS_Order { get; set; }
        public string DS_Amount { get; set; }
        public string DS_MerchantCode { get; set; }
        public string DS_Terminal { get; set; }
        public string DS_Currency { get; set; }
        public string DS_Signature { get; set; }
        public string DS_TransactionType { get; set; }
        public string DS_Response { get; set; }
        public string DS_MerchantData { get; set; }
        public string DS_SecurePayment { get; set; }
        public string DS_Card_Country { get; set; }
        public string DS_AuthorisationCode { get; set; }
        public string DS_consumerLanguage { get; set; }
        public string DS_Card_Type { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
