//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transporte_SeguimientoManual
    {
        public Nullable<System.DateTime> message_creation { get; set; }
        public string CEstado { get; set; }
        public string CDescripcion { get; set; }
        public Nullable<int> IdTransporteCab { get; set; }
        public int ID { get; set; }
    }
}
