//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transporte_Ponderada
    {
        public int ID { get; set; }
        public Nullable<float> A { get; set; }
        public Nullable<float> B { get; set; }
        public Nullable<float> C { get; set; }
        public Nullable<float> D { get; set; }
        public string Servicio { get; set; }
    }
}
