//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transporte_Message
    {
        public int ID { get; set; }
        public Nullable<int> IdTransporteCab { get; set; }
        public string TipoRequest { get; set; }
        public string message_id { get; set; }
        public string message_service { get; set; }
        public string message_creation { get; set; }
        public string data_state { get; set; }
        public string data_success { get; set; }
        public string data_id { get; set; }
        public string data_description { get; set; }
        public string data_service { get; set; }
        public string data_process { get; set; }
        public string data_division { get; set; }
        public string data_logisticsGroup { get; set; }
        public string data_customer { get; set; }
        public string data_load { get; set; }
        public string data_commodity { get; set; }
        public string data_ref { get; set; }
        public string route_sequence { get; set; }
        public string route_load { get; set; }
        public string origen_type { get; set; }
        public string origen_country { get; set; }
        public string origen_code { get; set; }
        public string origen_city { get; set; }
        public string origen_latitude { get; set; }
        public string origen_longitude { get; set; }
        public string origen_postal { get; set; }
        public string origen_name { get; set; }
        public string destino_type { get; set; }
        public string destino_country { get; set; }
        public string destino_code { get; set; }
        public string destino_city { get; set; }
        public string destino_latitude { get; set; }
        public string destino_longitude { get; set; }
        public string destino_postal { get; set; }
        public string destino_name { get; set; }
        public string shipment_state { get; set; }
        public string shipment_success { get; set; }
        public string shipment_id { get; set; }
        public string shipment_service { get; set; }
        public string shipment_process { get; set; }
        public string shipment_customer { get; set; }
        public string shipment_load { get; set; }
        public string shipment_ref { get; set; }
        public string shipment_result { get; set; }
        public string shipment_division { get; set; }
        public string shipment_logisticsGroup { get; set; }
        public string shipment_commodity { get; set; }
        public string reference_value_SREF { get; set; }
        public string reference_type_SREF { get; set; }
        public string reference_value_INFO1 { get; set; }
        public string reference_value_INFO2 { get; set; }
        public string reference_value_INFO3 { get; set; }
        public string reference_type_INFO1 { get; set; }
        public string reference_type_INFO2 { get; set; }
        public string reference_type_INFO3 { get; set; }
        public string container_id { get; set; }
        public string container_ref { get; set; }
        public string container_model { get; set; }
        public string container_weight { get; set; }
        public string container_volume { get; set; }
        public string route1_state { get; set; }
        public string route1_sequence { get; set; }
        public string route1_load { get; set; }
        public string route1_pickDate { get; set; }
        public string route2_state { get; set; }
        public string route2_sequence { get; set; }
        public string route2_load { get; set; }
        public string route2_dropDate { get; set; }
    }
}
