//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transporte_Agenda
    {
        public int Id { get; set; }
        public System.Guid UserId { get; set; }
        public string RazonSocial { get; set; }
        public string Actividad { get; set; }
        public string Contacto { get; set; }
        public string DNI { get; set; }
        public string Provincia { get; set; }
        public string Localidad { get; set; }
        public string Direccion { get; set; }
        public string Numero { get; set; }
        public string CP { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<bool> Particular_Empresa { get; set; }
        public string Empresa { get; set; }
        public string CIF { get; set; }
        public Nullable<int> IdProvincia { get; set; }
        public string Observaciones { get; set; }
        public string Movil { get; set; }
        public Nullable<System.DateTime> Creacion { get; set; }
    }
}
