//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transporte_Transportista
    {
        public int ID { get; set; }
        public string Transportista { get; set; }
        public string RazonSocial { get; set; }
        public string NIF { get; set; }
        public string Direccion { get; set; }
        public string CodigoPostal { get; set; }
        public string Localidad { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public string Email2 { get; set; }
        public string Telefono2 { get; set; }
        public string Contacto { get; set; }
        public string Contacto2 { get; set; }
    }
}
