//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportePedidosLin
    {
        public int ID { get; set; }
        public string Matricula { get; set; }
        public Nullable<System.DateTime> FechaDisponibilidad { get; set; }
        public string RazonSocialRecogida { get; set; }
        public string ContactoRecogida { get; set; }
        public string TelefonoRecogida { get; set; }
        public string ProvinciaRecogida { get; set; }
        public string LocalidadRecogida { get; set; }
        public string DireccionRecogida { get; set; }
        public string CodigoPostalRecogida { get; set; }
        public string ObservacionRecogida { get; set; }
        public string RazonSocialEntrega { get; set; }
        public string ContactoEntrega { get; set; }
        public string TelefonoEntrega { get; set; }
        public string DNIEntrega { get; set; }
        public string ProvinciaEntrega { get; set; }
        public string LocalidadEntrega { get; set; }
        public string DireccionEntrega { get; set; }
        public string CodigoPostalEntrega { get; set; }
        public string ObservacionEntrega { get; set; }
        public Nullable<int> Tipo { get; set; }
        public Nullable<int> Largo { get; set; }
        public Nullable<int> Alto { get; set; }
        public Nullable<int> Peso { get; set; }
        public string Servicio { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Clase { get; set; }
        public Nullable<int> IdPedidoCab { get; set; }
        public Nullable<bool> Arranca { get; set; }
    }
}
