//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transporte_PagoTPV
    {
        public int ID { get; set; }
        public string Matricula { get; set; }
        public Nullable<System.DateTime> FechaSolicitud { get; set; }
        public Nullable<System.DateTime> FechaDisponibilidad { get; set; }
        public Nullable<System.DateTime> FechaRecogida { get; set; }
        public string RazonSocialRecogida { get; set; }
        public string ContactoRecogida { get; set; }
        public string TelefonoRecogida { get; set; }
        public string ProvinciaRecogida { get; set; }
        public string LocalidadRecogida { get; set; }
        public string DireccionRecogida { get; set; }
        public string CodigoPostalRecogida { get; set; }
        public string ObservacionRecogida { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public string RazonSocialEntrega { get; set; }
        public string ContactoEntrega { get; set; }
        public string TelefonoEntrega { get; set; }
        public string DNIEntrega { get; set; }
        public string ProvinciaEntrega { get; set; }
        public string LocalidadEntrega { get; set; }
        public string DireccionEntrega { get; set; }
        public string CodigoPostalEntrega { get; set; }
        public string ObservacionEntrega { get; set; }
        public string PuertoEmbarque { get; set; }
        public Nullable<float> TarifaPonderadaA { get; set; }
        public Nullable<float> TarifaPonderadaB { get; set; }
        public Nullable<float> TarifaPonderadaC { get; set; }
        public Nullable<float> TarifaReferenciaA { get; set; }
        public Nullable<float> TarifaReferenciaB { get; set; }
        public Nullable<float> TarifaReferenciaC { get; set; }
        public Nullable<float> SumaPonderada { get; set; }
        public string TransporteDirecto { get; set; }
        public string TransporteIndirectoA { get; set; }
        public string TransporteIndirectoB { get; set; }
        public string ModoA { get; set; }
        public string ModoB { get; set; }
        public string ModoC { get; set; }
        public Nullable<float> EquivalenciaTerrestre { get; set; }
        public Nullable<float> EquivalenciaMaritima { get; set; }
        public Nullable<float> CoeficienteTerrestre { get; set; }
        public Nullable<float> CoeficienteMaritimo { get; set; }
        public Nullable<int> Tipo { get; set; }
        public Nullable<int> Largo { get; set; }
        public Nullable<int> Alto { get; set; }
        public Nullable<int> Peso { get; set; }
        public Nullable<float> PonderacionBasica { get; set; }
        public Nullable<float> PonderacionExpress { get; set; }
        public string Servicio { get; set; }
        public Nullable<float> PrecioBase { get; set; }
        public string IdTPV { get; set; }
        public Nullable<int> IdTVersion { get; set; }
        public string MatriculasDS { get; set; }
        public Nullable<System.Guid> IdUsuario { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Clase { get; set; }
        public Nullable<bool> Arranca { get; set; }
    }
}
