//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transporte_Referencia
    {
        public int ID { get; set; }
        public string Origen { get; set; }
        public string Destino { get; set; }
        public string Codigo { get; set; }
        public Nullable<float> TarifaReferencia { get; set; }
        public string Modo { get; set; }
    }
}
