//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuariosDatosBancarios
    {
        public int Id { get; set; }
        public System.Guid PKID { get; set; }
        public string Titular { get; set; }
        public string NombreBanco { get; set; }
        public string CCBanco { get; set; }
        public string CCOficina { get; set; }
        public string CCCodControl { get; set; }
        public string CCNumCuenta { get; set; }
        public short diaCobro { get; set; }
        public string IBAN { get; set; }
        public string BIC { get; set; }
    }
}
