//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuariosServiciosFacturados
    {
        public System.Guid IdUsuario { get; set; }
        public decimal Mes { get; set; }
        public decimal Year { get; set; }
        public int IdUsuariosServicios { get; set; }
        public int IdUsuariosServiciosFacturados { get; set; }
        public int IdEmpresa { get; set; }
    }
}
