//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.Alertas = new HashSet<Alertas>();
            this.Financiacion_Solicitud = new HashSet<Financiacion_Solicitud>();
            this.Financiacion_Solicitud1 = new HashSet<Financiacion_Solicitud>();
            this.Financiacion_Usuario_Banco = new HashSet<Financiacion_Usuario_Banco>();
            this.Financiacion_Usuario_Datos = new HashSet<Financiacion_Usuario_Datos>();
        }
    
        public System.Guid Id { get; set; }
        public string Nombre { get; set; }
        public string NombreUrl { get; set; }
        public string Apellidos1 { get; set; }
        public string Apellidos2 { get; set; }
        public string Nif { get; set; }
        public string Direccion { get; set; }
        public string CodigoPostal { get; set; }
        public string Localidad { get; set; }
        public string Provincia { get; set; }
        public Nullable<int> Comunidad { get; set; }
        public string Pais { get; set; }
        public string Telefono { get; set; }
        public string Fax { get; set; }
        public string Movil { get; set; }
        public string Email { get; set; }
        public string Web { get; set; }
        public string Observaciones { get; set; }
        public Nullable<double> MapX { get; set; }
        public Nullable<double> MapY { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public Nullable<int> NumeroCliente { get; set; }
        public Nullable<int> ProvinciaID { get; set; }
        public Nullable<int> LocalidadID { get; set; }
        public string PersonaContacto { get; set; }
        public string Comentarios { get; set; }
        public string Logo { get; set; }
        public Nullable<int> NumMaxAnuncios { get; set; }
        public int Id2 { get; set; }
        public Nullable<bool> OfertasConcesionarios { get; set; }
        public Nullable<bool> BoletinSemanal { get; set; }
        public Nullable<int> IdMarcaConcesionario { get; set; }
        public string NumeroAfiliado { get; set; }
        public string PersContactoMovil3 { get; set; }
        public string PersContactoMovil2 { get; set; }
        public string PersContactoMovil1 { get; set; }
        public string Telefono1 { get; set; }
        public string PersonaContacto3 { get; set; }
        public string PersonaContacto2 { get; set; }
        public string DniAdministrador1 { get; set; }
        public string Administrador2 { get; set; }
        public string Administrador1 { get; set; }
        public string NombreFiscal { get; set; }
        public string Email2 { get; set; }
        public string DniAdministrador2 { get; set; }
        public Nullable<bool> ZonaA { get; set; }
        public Nullable<bool> ZonaB { get; set; }
        public bool Deudor { get; set; }
        public Nullable<int> TipoEstablecimiento { get; set; }
        public Nullable<int> IdMarca { get; set; }
        public string OtrosEstablecimiento { get; set; }
        public bool tvCoches { get; set; }
        public bool tvCamiones { get; set; }
        public bool tvRecambios { get; set; }
        public bool tvOtros { get; set; }
        public string OtrosTipoVehiculos { get; set; }
        public Nullable<int> idComunidadFiscal { get; set; }
        public Nullable<int> idProvinciaFiscal { get; set; }
        public Nullable<int> idLocalidadFiscal { get; set; }
        public string codPostalFiscal { get; set; }
        public string emailContacto1 { get; set; }
        public string emailContacto2 { get; set; }
        public string emailContacto3 { get; set; }
        public string direccionFiscal { get; set; }
        public bool tvMotos { get; set; }
        public string sesionID { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public Nullable<System.DateTime> fechaAlta { get; set; }
        public Nullable<System.DateTime> fechaBaja { get; set; }
        public int id_tipo_usuario { get; set; }
        public Nullable<int> TipoPago { get; set; }
        public Nullable<bool> chk_email { get; set; }
        public Nullable<bool> chk_email2 { get; set; }
        public Nullable<bool> chk_emailcontacto1 { get; set; }
        public Nullable<bool> chk_emailcontacto2 { get; set; }
        public Nullable<bool> chk_emailcontacto3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alertas> Alertas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Financiacion_Solicitud> Financiacion_Solicitud { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Financiacion_Solicitud> Financiacion_Solicitud1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Financiacion_Usuario_Banco> Financiacion_Usuario_Banco { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Financiacion_Usuario_Datos> Financiacion_Usuario_Datos { get; set; }
        public virtual TipoUsuario TipoUsuario { get; set; }
        public virtual Users Users { get; set; }
    }
}
