//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehiculoSeguroFlotante
    {
        public Nullable<System.Guid> Id_borrar { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Matricula { get; set; }
        public int IdSeguroFlotante { get; set; }
        public int Id { get; set; }
    
        public virtual SeguroFlotante SeguroFlotante { get; set; }
    }
}
